import React, { useState } from "react";
import Head from "next/head";
import { Box } from "@/components/models";
import { colors, sources } from "@/theme";
import { LoginForm, SignUpForm } from "@/components/sets";

export default function LoginPage()
{
    const [form, setForm] = useState(false)

    const changeForm = (event: React.MouseEvent) => {
        event.preventDefault()
        setForm(!form)
    } 

    return (
        <>
            <Head>
                <title>Scientific event - Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box backgroundImage={sources.loginBackground} height="100%" backgroundSize="cover">
                <Box linearGradient={{
                    c1: colors.c3, 
                    c2: colors.transparent,
                    degrees: "45deg"
                }} 
                height="100%" 
                display="flex" 
                justifyContent="center" 
                alignItems="center">
                    {form
                    ?<SignUpForm changeForm={changeForm}/>
                    :<LoginForm changeForm={changeForm}/>
                    }
                    
                </Box>
            </Box>
        </>
    )
}