import React from "react";
import Head from "next/head";
import { Box, Form } from "@/components/models";
import { colors, sources } from "@/theme";

export default function LoginPage()
{
    return (
        <>
            <Head>
                <title>Scientific event - Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box backgroundImage={sources.loginBackground} height="100%" backgroundSize="cover">
                <Box linearGradient={{
                    c1: colors.c3, 
                    c2: colors.transparent, 
                    degrees: "45deg"
                }} 
                height="100%" 
                display="flex" 
                justifyContent="center" 
                alignItems="center">
                    <Form 
                    formSize={{
                        lg: { width: 400, height: 500 },
                        md: { width: 350, height: 400 },
                    }} 
                    backgorundColor={colors.c2}
                    borderRadius="10px">
                        
                    </Form>
                    
                </Box>
            </Box>
        </>
    )
}