import React from "react";
import { ArticlesViewer } from "@/components/sets";
import Head from "next/head";
import { Box } from "@/components/models";

import { widths, thickness, colors } from "@/theme";

const ArticlesPage = () => {
    return (
        <>
            <Head>
                <title>Scientific Event - Articles</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <Box 
            width={widths.w1} 
            height={widths.w1} 
            display="flex" 
            flexDirection="column"
            borderWidth={thickness.t1}
            borderColor={colors.c4}
            backgroundColor={colors.c4}>
                <ArticlesViewer/>
            </Box>
        </>
    )
}

export default ArticlesPage