import React from "react";
import { ArticlesViewer } from "@/components/sets";
import Head from "next/head";
import { Box } from "@/components/models";

const ArticlesPage = () => {
    return (
        <>
            <Head>
                <title>Scientific Event - Articles</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <ArticlesViewer/>
        </>
    )
}

export default ArticlesPage