import React from "react";
import { ArticlesList } from "@/components/sets";
import Head from "next/head";

const ArticlesPage = () => {
    return (
        <>
            <Head>
                <title>Scientific Event - Articles</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <ArticlesList/>
        </>
    )
}

export default ArticlesPage