import { useRouter } from "next/router"
import { useState, useEffect } from "react"

import { colors, sources, widths } from "@/theme"

import Head from "next/head"
import { Box } from "@/components/models"
import { Footer, Header, ArticlesSubmitForm } from "@/components/sets"
import { getCookie } from "cookies-next"

const HomePage = () => {
    const [user, setUser] = useState({
        username: "",
        email: "",
        admin: false,
    })
    
    useEffect(() => {
        (async function getActualUser() { 
            const pUser = {
                ...JSON.parse(String(localStorage.getItem("user"))),
                admin: Number(getCookie("admin"))
            }

            setUser(pUser)
        })()
    }, [])

    return ( 
        <>
            <Head>
                <title>Scientific event - Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                
            </Head>
            <Box 
            alignItems="center"
            backgroundSize="cover"
            backgroundImage={sources.homeBackground} 
            borderColor={colors.c4}
            borderWidth="10px"
            display="flex" 
            flexDirection="column"
            id="auto-page-height"  
            height={widths.w1}
            width={widths.w1}
            overflow="hidden">
                <Header user={user}/>
                
                <Box 
                as="main" 
                display="flex"
                flexGrow="1"  
                alignItems="center"
                justifyContent="space-around"
                width={widths.w1}>
                    <ArticlesSubmitForm email={user.email}/>
                </Box>

                <Footer/>
            </Box>
        </>
    )
}

export default HomePage