import { getuser } from "@/utils/api-connection"
import { useRouter } from "next/router"
import { useState, useEffect } from "react"

import { colors, sources, widths } from "@/theme"

import Head from "next/head"
import { Button, Box } from "@/components/models"
import { Header } from "@/components/sets"


const HomePage = () => {
    const [user, setUser] = useState({
        username: "",
        email: "",
        admin: false,
    })
    
    const router = useRouter()

    useEffect(() => {
        (async function getActualUser() { setUser(await getuser(router)) })()
    }, [])

    return ( 
        <>
            <Head>
                <title>Scientific event - Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <Box 
            alignItems="center"
            backgroundSize="cover"
            backgroundImage={sources.homeBackground} 
            display="flex" 
            flexDirection="column" 
            height={widths.w1} 
            width={widths.w1}>
                <Header/>
            </Box>
        </>
    )
}

export default HomePage